import { StyleSheet } from 'react-native';
import { colors } from './theme';

const formCard = {
  backgroundColor: colors.surface,
  borderColor: colors.border,
  borderWidth: 1,
  borderRadius: 22,
  padding: 24,
  marginHorizontal: 16,
  marginVertical: 16,
  width: '92%' as const,
  maxWidth: 440,
  alignSelf: 'center' as const,
};

const input = {
  minHeight: 52,
  borderWidth: 1,
  borderColor: colors.border,
  borderRadius: 12,
  paddingHorizontal: 15,
  color: colors.text,
  backgroundColor: colors.surfaceRaised,
  marginBottom: 18,
  fontSize: 16,
};

const primaryButton = {
  minHeight: 52,
  backgroundColor: colors.red,
  borderRadius: 12,
  alignItems: 'center' as const,
  justifyContent: 'center' as const,
  marginTop: 6,
  paddingHorizontal: 18,
};

export const appStyles = StyleSheet.create({
  rootContainer: { flex: 1, backgroundColor: 'transparent' },
  loadingContainer: { flex: 1, backgroundColor: colors.background, alignItems: 'center', justifyContent: 'center' },
  loadingIndicator: { marginTop: 20 },
  backgroundImage: { flex: 1, backgroundColor: colors.background },
  headerContainer: { alignItems: 'center', paddingTop: 20, paddingBottom: 10 },
  logoImage: { width: 188, height: 72 },
  signInContainer: { ...formCard },
  signUpContainer: { ...formCard, paddingBottom: 28 },
  forgotPasswordContainer: { ...formCard },
  signUpTitle: { color: colors.text, fontSize: 28, fontWeight: '800', marginBottom: 7 },
  forgotPasswordTitle: { color: colors.text, fontSize: 28, fontWeight: '800', marginBottom: 7 },
  formSubtitle: { color: colors.muted, fontSize: 15, lineHeight: 22, marginBottom: 25 },
  inputLabel: { color: colors.text, fontSize: 13, fontWeight: '700', marginBottom: 9 },
  input,
  passwordInput: input,
  phoneFieldContainer: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  countryCodePicker: {
    width: 93,
    height: 52,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    backgroundColor: colors.surfaceRaised,
    overflow: 'hidden',
    marginBottom: 18,
    justifyContent: 'center',
  },
  picker: { color: colors.text, backgroundColor: colors.surfaceRaised },
  phoneInput: { ...input, flex: 1 },
  signUpButton: primaryButton,
  sendCodeButton: primaryButton,
  signInButtonDisabled: { opacity: 0.6 },
  signUpButtonDisabled: { opacity: 0.6 },
  buttonDisabled: { opacity: 0.6 },
  signUpButtonText: { color: colors.text, fontSize: 16, fontWeight: '800' },
  buttonText: { color: colors.text, fontSize: 16, fontWeight: '800' },
  signInLink: { alignItems: 'center', justifyContent: 'center', minHeight: 44, marginTop: 5 },
  signInLinkText: { color: colors.redLight, fontSize: 15, fontWeight: '700' },
  guestModeButton: {
    minHeight: 50,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 13,
  },
  guestModeText: { color: colors.text, fontSize: 15, fontWeight: '700' },
  backToSignIn: { alignItems: 'center', justifyContent: 'center', minHeight: 48, marginTop: 10 },
  backToSignInText: { color: colors.redLight, fontSize: 15, fontWeight: '700' },
});
